name: Build
on: [push, pull_request]

jobs:
  run-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build
