name: format
on: [push, pull_request]

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node.js environment
        uses: actions/setup-node@main
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check format
        run: yarn run format:check
